import React from "react";
import { Helmet } from "react-helmet";
import FooterWebsite from "../../Component/Footer/FooterWebsite";
import Navbar from "../../Layout/Navbar";

const TermsConditions = () => {
    return (
        <div>
            <div>
                <Navbar />
                <div className="main-container">
                    <section>
                        <div className="container">
                            <div className="row justify-content-center">
                                <div className="col-md-10 col-lg-8">
                                    <article>
                                        <div className="article__title text-center">
                                            <h1 className="h2">
                                                Terms and Conditions of Use
                                            </h1>
                                            <span>
                                                Last Update: Jan 28, 2024
                                            </span>
                                        </div>
                                        <div className="article__body">
                                            <p>U-Greet Inc. (<strong>“U-Greet”,</strong> "<strong>we</strong>", "<strong>us</strong>" or "<strong>our</strong>") is a corporation formed pursuant to the <em>Canada Business Corporations Act</em> (R.S.C., 1985, c. C-44). In consideration for permitting your access to our website and online services and other good and valuable consideration, you agree as follows:</p>
                                            <p>These terms and conditions (the "<strong>Terms</strong>") form a legally binding agreement which govern your access to and use of our website, our online web-application hosted at <a href="http://app.u-greet.com">http://app.u-greet.com</a> and any related iOS and Android mobile applications (not currently available) which we may subsequently make available.  Collectively our mobile applications (if made available), website and web-application are referred to in these Terms as the “<strong>U-Greet</strong> <strong>Platform</strong>”.</p>
                                            <p><strong>These Terms have provisions which limit our liability and impose obligations on you.</strong> You must review these Terms carefully before using the U-Greet Platform. By using U-Greet Platform, you, the user ("<strong>you</strong>" or "<strong>your</strong>"), represent and warrant that (i) you are at least 18 years old; and (ii) you have read and understand these Terms and agree to be bound by them.</p>
                                            <p>If you are using the U-Greet Platform on behalf of, or in the employ of, an organization (corporation, trust, partnership, etc.), you are agreeing to these Terms for that organization and representing and warranting that you have the authority to bind that organization to these Terms. In such a case, "you" and "your" will also refer to that organization and yourself individually. For greater clarity, both you as an individual and your organization are legally bound by these Terms which form an agreement between you and U-Greet Inc.</p>
                                            <p><strong>AMENDMENTS&nbsp;</strong></p>
                                            <p>As the U-Greet Platform continues to evolve, we may, at any time, revise these Terms and our policies by updating this page or the page hosting the relevant policy. The date of the last version of these Terms is posted above.  As you are bound by these Terms each time you use the U-Greet Platform, you are responsible for periodically reviewing the amendments to these Terms and you are deemed to have accepted and agreed to such amendments by accessing and using the U-Greet Platform after such amendments have been posted. If you do not agree with the amendments, you shall immediately stop accessing the U-Greet Platform and terminate your account, subject to the terms provided for herein. We may also undertake to send you an email and/or display notice of any changes to the Terms or policies in your account.&nbsp;</p>
                                            <p><strong>PRIVACY</strong></p>
                                            <p>We use personal information you provide to us in accordance with our privacy policy, which is incorporated by reference and available online at <a href="http://app.u-greet.com/PrivacyPolicy">http://app.u-greet.com/PrivacyPolicy</a>. By accepting these Terms, you consent to such processing, and you represent to us that all information provided by you is accurate.&nbsp;</p>
                                            <p><strong>About Our Online Service</strong></p>
                                            <p>The U-Greet Platform allows you and other users to upload videos, photos and other content to create and share memorable greeting videos.</p>
                                            <p>To use the U-Greet Platform you will be required to register an account and provide certain personal information as referenced in our privacy policy. We may also allow the invitees of account holders, as guest contributors, to upload content. As a guest contributor you will be required to accept these Terms prior to uploading content and you agree that these Terms apply to you and your use of the U-Greet Platform.&nbsp;</p>
                                            <p>Regardless of whether you pay for an account or not, or access the platform as a guest contributor, you agree that access to the U-Greet Platform constitutes good and valuable consideration in exchange for agreeing to these Terms our privacy policy and all other documents and policies incorporated by reference.&nbsp;</p>
                                            <p>Upon establishing an account or uploading content as a guest contributor, we grant you a non-transferable, non-exclusive license to access the U-Greet Platform in accordance with these Terms. However, we reserve the right to revoke that license and your access to the U-Greet Platform at any time. We make no representations or warranties as to the ongoing availability of the U-Greet Platform, or your access to it.&nbsp;</p>
                                            <p><strong>Account Not Transferrable</strong></p>
                                            <p>Access to your account is not transferrable and is only intended for you, the individual who established the account, even if your account is paid for by someone else or made accessible to you by an organization (such as your employer or other third party). As a result, you are not permitted to change the name associated with your account.&nbsp;</p>
                                            <p><strong>Account Security</strong></p>
                                            <p>Upon setting up an account, you will be required to create a username and password. You are responsible for safeguarding the password you use to access the U-Greet Platform and you agree not to disclose your password to any third-party. </p>
                                            <p>You agree to use a unique password for your account which you do not use for any other online service. As we may send password reset notices and links to your email account registered on the U-Greet Platform (i) you are responsible for ensuring that the email address provided on the platform is accurate; and (ii) you represent and warrant to us, and agree that you will ensure, you are the sole person, at all times, with access to the email account registered in connection with your account.</p>
                                            <p>You agree you are responsible for any activity on your account and all correspondence provided to us from any email address or phone number used to register your account, whether or not you authorized that activity or correspondence. You agree that we are, in respect of any instructions or actions taken by a person using your account, entitled to assume that the person is you; the person whose name and personal information is registered and associated with the account.</p>
                                            <p>You must immediately notify us of any unauthorized use of your account.&nbsp;</p>
                                            <p>You must inform us of any changes to your contact details and other information provided to us, including, but not limited to, your email address.&nbsp;</p>
                                            <p>While we and our third party software and technology providers take certain security measures in relation to the U-Greet Platform, you acknowledge that the technical processing and transmission of the U-Greet Platform and related data and information, including your own account data and information will involve transmissions over various networks and devices (such as third party servers for hosting data), including networks and devices not owned or controlled by us. We rely on a number of third parties to make the U-Greet Platform available, including data and web hosting providers. You accept all risks arising from the use of such third party networks and devices when using the U-Greet Platform and you acknowledge that in using online platforms, there is a risk of unauthorized access to and use of your information, including your personal information, videos and photos.&nbsp;</p>
                                            <p><strong>Acceptable Use of the U-Greet Platform</strong></p>
                                            <p>In using the U-Greet Platform, you agree, and you represent and warrant to us and all other users of the platform, that you:</p>
                                            <ol>
                                                <li>Will not use the U-Greet Platform in a way that has any unlawful or fraudulent purpose or effect;</li>
                                                <li>Will comply with all applicable laws, rules and regulations;  </li>
                                                <li>Will not use or disclose personal or personally identifiable information belonging to others (including for example, their images, videos in which they appear, email address and phone number) except (i) with their consent; and (ii) in accordance with applicable privacy laws, rules and regulations;</li>
                                                <li>Will not invite or send messages to guest contributors via the platform, using their phone number, email address or other means of communication, whether to invite them to use platform or otherwise, without their consent;&nbsp;</li>
                                                <li>Will not upload, copy, distribute, share or otherwise use or generate data or content that is unlawful, obscene, defamatory, offensive, contrary to our morals, libelous, harmful, hateful, harassing, bullying, sexual in nature, threatening, racially or ethnically offensive or abusive, that would violate a third party’s rights (including their intellectual property rights), constitute or encourage a criminal offense or give rise to civil liability or damages;</li>
                                                <li>Will not upload, transmit, disseminate, post, share, store, use any content, data or information, perform any services or do anything that infringes on, or contributes to any infringement of, any intellectual property rights; including copyright, trademark, patent or trade secret rights, whether of ours or any third party;</li>
                                                <li>Will not disclose your password or transfer your account to any third party, or allow any third party to access your account;</li>
                                                <li>Will not impersonate any person or entity;</li>
                                                <li>Will not upload or otherwise provide us information which is confidential in nature or subject to a contractual or other duty as to confidentiality;</li>
                                                <li>Will not upload, copy, distribute, share, create or otherwise use content, code or information that contains or embodies software viruses or any other malicious computer code that is designed to interrupt, undermine, destroy or limit the functionality of any computer software, hardware or communications equipment, or that is designed to perform functions on any software, hardware or equipment without the owner's express consent;</li>
                                                <li>Will not access the U-Greet Platform by any means other than through the interface provided by us for use, whether via the mobile apps, websites or our API, if we make one available. </li>
                                                <li>Will not use any software bot or data scraping techniques that accesses the U-Greet Platform to scrape or pull data for any purpose, whether such data was displayed publicly or not.&nbsp;</li>
                                                <li>Will not collect, harvest or store any personally identifiable information, including user account information, from us;</li>
                                                <li>Will not translate, reverse engineer, decompile, disassemble, modify or create derivative works based on the U-Greet Platform and its underlying software code; and</li>
                                                <li>Will not circumvent, disable, violate or otherwise interfere with any security related feature of the U-Greet Platform.</li>
                                            </ol>
                                            <p>We may, but have no obligation to, remove accounts, guest contributors, users and/or content from the U-Greet Platform that we determine, in our sole discretion, to have, or which may reasonably appear to have, violated these Terms.</p>
                                            <p><strong>If you are an account holder, and a guest contributor uploads content in connection with your account which violates these Terms, it shall be your obligation to delete such content and you agree that you may be liable to us and others for any failure to delete or remove content that infringes a third party’s intellectual property rights, or which is otherwise unlawful or a breach of these Terms.&nbsp;</strong></p>
                                            <p><strong>Fees and Taxes</strong></p>
                                            <p>Our fees for using the U-Greet Platform are displayed on the platform, including as part of the checkout process. You agree to pay all fees associated with or arising from your account, as displayed on the platform, for any order placed or subscription made by your account.&nbsp;</p>
                                            <p>Our fees are subject to change and we may update pricing on the platform at any time. Thereafter, you agree to pay all updated fees for any subsequent orders.&nbsp;</p>
                                            <p>If you subscribe to a monthly or other ongoing minimum subscription duration (to have favorable pricing on a per video basis), we will provide you with email notice of any increase to your subscription fees. Such notice will be provided to you at least 30 calendar days prior to the end of the subscription duration. During that time, you may elect to not renew your subscription from within your account. Otherwise, your subscription will automatically renew, for the same duration, at the prices specified.&nbsp;</p>
                                            <p>You agree to pay all sales taxes, whether Canadian or foreign, applicable to these Terms, purchases you make on the platform or arising in any way from your account and access to and use of the U-Greet Platform.&nbsp;</p>
                                            <p>Additional terms, including terms related to sales tax, refunds and payment processing may be specified on the U-Greet Platform. Those terms, as amended from time to time, are incorporated by reference and form part of this agreement. </p>
                                            <p><strong>Payment</strong></p>
                                            <p>We facilitate payment on the U-Greet Platform using Stripe, Inc., Stripe Payments Canada, Ltd. and their related entities (collectively “<strong>Stripe</strong>”). For more information on Stripe’s privacy practices visit <a href="https://stripe.com/en-ca/privacy">https://stripe.com/en-ca/privacy</a>. Accordingly, when you input your card payment information in connection with an order on our platform, you are providing that information to Stripe.&nbsp;</p>
                                            <p>While we may have the ability to bill your card via Stripe, have access to certain information related to your payments, like the name on your card, the last four digits of the card and other information, we will not have access to your full card number.&nbsp;</p>
                                            <p><strong>Refunds</strong></p>
                                            <p>Given the nature of our platform, orders placed (and for which payments have been processed) and subscriptions made are non-refundable. Accordingly, you agree that we may bill your payment method for any orders placed via your account and subscriptions which automatically renew each month (or other subscription duration period specified within your account).&nbsp;</p>
                                            <p>In order to cancel a subscription, you must do so at least 3 days prior to the subscription period’s renewal (from within your account), otherwise you will be automatically billed, and your payment method charged, for the subsequent subscription period.&nbsp;</p>
                                            <p><strong>Subscription Cancellation Charges</strong></p>
                                            <p>To obtain favorable pricing on a per video basis, the Platform may specify a minimum subscription duration, for example a 12 month subscription. Should you cancel your subscription prior to the minimum subscription duration, you agree that you will be retroactively charged, and we will bill your payment method, for past videos, at the then current per video rate for non-subscribers. </p>
                                            <p><strong><u>ACCEPTANCE OF RISK AND DISCLAIMERS</u></strong></p>
                                            <p><strong>Our U-Greet Platform is provided "as is" without warranty of any kind, including but not limited to, all implied warranties and conditions of merchantability and fitness for a particular purpose. To the fullest extent permitted by applicable law, we hereby disclaim all warranties and conditions of any kind, whether express, implied or statutory.</strong></p>
                                            <p><strong>Without limiting any other section of these Terms, to the fullest extent permitted by law, you agree that we shall not be responsible for any damages you suffer arising from the acts or omissions, including the negligent acts or omissions, of other users on the U-Greet Platform, our independent contractors, web and data hosting providers, payment processors or third-party service providers.</strong></p>
                                            <p><strong>While we strive to have the U-Greet Platform error free and uninterrupted, we do not guarantee the absence of errors or interruptions. You agree that we shall not be held liable for any damage such errors or interruptions may cause. We make no representations and grant no warranties as to the uptime of the U-Greet Platform.&nbsp;</strong></p>
                                            <p><strong>We may also perform scheduled maintenance which will result in the U-Greet Platform being unavailable for certain periods of time.&nbsp;</strong></p>
                                            <p><strong>While users are required to comply with these Terms, including the acceptable use terms listed above, we make no representations and grant no warranties that other users have in fact or will in fact, comply with all such terms.</strong></p>
                                            <p><strong>We make no representations and grant no warranties as to the content uploaded by or offered by other users on U-Greet Platform. We have not conducted any background checks or verified the identity of other users.&nbsp;</strong></p>
                                            <p><strong>You acknowledge and agree that we have no control over and do not guarantee the quality, safety, suitability, or legality of any content made available by other users on the U-Greet Platform, the truth or accuracy of any user content posted by other users, or the performance or conduct of any other user.</strong></p>
                                            <p><strong><u>Limitation of our liability</u></strong></p>
                                            <p><strong>YOU AGREE THAT TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL WE, OUR OFFICERS, DIRECTORS, SHAREHOLDERS OR EMPLOYEES, BE LIABLE TO YOU FOR ANY DAMAGES YOU MAY SUFFER IN CONNECTION WITH YOUR USE, OR FAILURE TO BE ABLE TO USE, THE&nbsp;</strong><strong>U-GREET</strong>&nbsp;<strong>PLATFORM</strong><strong>, HOWSOEVER CAUSED, INCLUDING BY NEGLIGENCE OR OTHERWISE AND REGARDLESS OF LEGAL THEORY AND WHETHER OR NOT WE HAVE BEEN WARNED OF THE POSSIBILITY OF SUCH DAMAGES AND WHETHER THOSE DAMAGES WERE FORESEEABLE OR NOT.</strong></p>
                                            <p><strong>WITHOUT LIMITING THE FOREGOING, YOU AGREE THAT TO THE FULLEST EXTENT PERMITTED BY LAW, THE ABOVE LIMITATIONS ON LIABILITY APPLY TO DIRECT, INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, EXEMPLARY AND CONSEQUENTIAL DAMAGES. ACCORDINGLY, SUBJECT TO APPLICABLE LAW, YOU AGREE THAT UNDER NO CIRCUMSTANCES WILL WE, OR THE OTHER INDIVIDUALS AND ENTITIES LISTED ABOVE, BE LIABLE TO YOU FOR ANY LOST PROFITS, LOST REVENUE, LOST INFORMATION, OR LOST DATA (INCLUDING LOST OR DELETED PHOTOS AND VIDEOS).</strong></p>
                                            <p><strong>IF YOU ARE DISSATISFIED WITH THE U-GREET PLATFORM, OR DO NOT AGREE WITH ANY PART OF THESE TERMS, OR HAVE ANY OTHER DISPUTE OR CLAIM WITH OR AGAINST US, OUR OFFICERS, DIRECTORS, SHAREHOLDERS OR EMPLOYEES, THEN, SUBJECT TO APPLICABLE LAW, YOUR REMEDIES ARE TO (I) CANCEL ANY ACTIVE SUBSCRIPTIONS; (II) TERMINATE YOUR ACCOUNT (IF APPLICABLE); AND (III) DISCONTINUE ACCESSING AND USING THE U-GREET PLATFORM.</strong></p>
                                            <p><strong>IN ADDITION TO YOUR AGREEMENT TO NOT HOLD THE ABOVE ENTITIES AND PERSONS LIABLE FOR ANY DAMAGES, IN THE EVENT A COURT OR ARBITRATOR OF COMPETENT JURISDICTION DECLINES TO UPHOLD SAID CLAUSE, OR IT IS OTHERWISE NOT ENFORCEABLE OR APPLICABLE, YOU AGREE THAT IN NO CIRCUMSTANCES SHALL THE AGGREGATE LIABILITY FOR ANY AND ALL CLAIMS RELATING TO OR IN ANY WAY ARISING FROM YOUR USE (OR FAILURE TO BE ABLE TO USE) THE U-GREET PLATFORM, OR IN ANY WAY RELATED TO THESE TERMS, BE MORE THAN THE LESSER OF (I) CAD $50.00 OR (II) THE AMOUNTS YOU HAVE PAID TO US IN CONNECTION WITH THE USE OF YOUR ACCOUNT OVER THE PREVIOUS ONE (1) MONTH, FROM THE DATE YOU FIRST RAISED YOUR CLAIM WITH US IN WRITING.</strong></p>
                                            <p><strong><u>YOU AGREE AND ACKNOWLEDGE THAT WE WOULD NOT ENTER INTO THIS AGREEMENT OR GRANT ACCESS TO THE U-GREET PLATFORM WITHOUT THESE RESTRICTIONS AND LIMITATIONS ON OUR LIABILITY.</u></strong></p>
                                            <p><strong><u>Indemnification&nbsp;</u></strong></p>
                                            <p><strong>You agree to indemnify us, our employees, shareholders, directors and officers, and to defend and hold each of them harmless, from any and all claims and liabilities (including reasonable legal fees) which may arise from (i) your actual or alleged violation of these Terms or any policy incorporated by reference; (ii) your actual or alleged violation of any third-party right; (iii) any claim for damages suffered by another user which you caused or contributed to; or (iv) any actual or alleged violation of these Terms by a guest contributor whom you invited to upload content to be associated with your account on the U-Greet Platform.&nbsp;</strong></p>
                                            <p><strong>Proprietary Rights&nbsp;</strong></p>
                                            <p>The U-Greet Platform contains open source and public domain content, licenced content as well as proprietary content owned by us and by third parties. You are not permitted to copy, use, or distribute any content (including but not limited to text, software code, images, trademarks, videos and audio) on the U-Greet Platform without the express consent of the owner.&nbsp;</p>
                                            <p>All rights, title, and interest in and to the U-Greet Platform are and will remain the exclusive property of U-Greet Inc. and our licensors.</p>
                                            <p>The U-Greet Platform and our content thereon, is protected by copyright, trademark and other laws of Canada, the United States, and foreign countries. You agree not to reproduce, modify or prepare derivative works, distribute, sell, transfer, publicly display, publicly perform, transmit, or otherwise use the U-Greet Platform or any of our content thereon, without our express written consent. </p>
                                            <p>You also agree not to copy, modify or reverse engineer the software code which underlies the U-Greet Platform.</p>
                                            <p>You are not permitted to use any trademark or trade name of U-Greet Inc., including our logo, without our express permission.</p>
                                            <p><strong>Your Content</strong></p>
                                            <p>The U-Greet Platform permits you and other users the ability to upload and post content ("<strong>User Content</strong>"). Subject to applicable law, you own your User Content. While it may be displayed on the U-Greet Platform, you (and the applicable account holder) can delete your User Content at any time from the Platform.&nbsp;</p>
                                            <p>While we reserve the right to do so, we do not pre-screen all User Content uploaded or posted to the U-Greet Platform by you or other users. However, if we reasonably believe that your User Content may violate these Terms or any third-party's rights, we may remove it from the platform without advanced notice to you.&nbsp;</p>
                                            <p>In connection with your User Content, you affirm, represent and warrant that you own or have the necessary licenses, rights, consents and/or permissions to use and authorize us to use all patent, trademark, trade secret, copyright or other proprietary rights in and to your User Content in the manner contemplated by the&nbsp;U-Greet Platform.</p>
                                            <p>You hereby grant us a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to use any of your User Content that you post or upload to the U-Greet Platform to facilitate the ordinary use of the U-Greet Platform. </p>
                                            <p>We do not consider proposals or ideas, including without limitation ideas for new products, technologies, promotions, product names, product feedback and product improvements you provide us (“<strong>Feedback</strong>”) to be confidential information. If you send any Feedback to us, you acknowledge and agree that we shall not be under any obligation of confidentiality with respect to the Feedback and nothing in these Terms limits or restricts our right to independently use, develop, evaluate, or market products or services, whether incorporating the Feedback or otherwise.</p>
                                            <p><strong>No Ongoing Storage of User Content</strong></p>
                                            <p>We are not a data, video or photo storage business. It is our current policy to keep any completed videos on the Platform for a period of six (6) months from their completion date. However, we may reduce that period or remove videos and content in our sole discretion. </p>
                                            <p>In the event a video remains uncompleted after the intended event date (as specified on the Platform), any User Content that was uploaded to the Platform may be deleted automatically by Platform, or manually by us, after a period of three (3) months.&nbsp;</p>
                                            <p><strong>ACCORDINGLY, IT IS YOUR OBLIGATION TO KEEP A COPY OF ALL COMPLETED VIDEOS AND ANY UNUSED INDIVIDUAL VIDEO CLIPS AND PHOTO YOU WISH TO KEEP.&nbsp;</strong></p>
                                            <p>We may also set account data and individual file size limits, in our sole discretion.&nbsp;</p>
                                            <p><strong>Copyright Notice</strong></p>
                                            <p>If you believe that your copyrighted work has been copied in a way that constitutes copyright infringement and is accessible on the U-Greet Platform, please notify us at <a href="mailto:info@u-greet.com">info@u-greet.com</a>. While we take no responsibility for any user who breaches your copyright or other intellectual property rights, we may, in our sole discretion and without liability, undertake to (i) contact the infringer on your behalf; (ii) cancel the infringer's account; and/or (ii) remove the content in question from our platform.&nbsp;</p>
                                            <p><strong>Linked Sites</strong></p>
                                            <p>Whether or not we are affiliated with websites or third-party vendors that may be linked to the U-Greet Platform, you agree that we are not responsible for their content. Internet links found on the U-Greet Platform, whether posted by us or a third party, are not an endorsement and we do not represent or warrant the accuracy or truth of the contents, or endorse the products, services or information found on said websites. You access those links and corresponding websites at your own risk.</p>
                                            <p><strong>Law of the Contract (Governing Law) and Jurisdiction.&nbsp;</strong></p>
                                            <p>These Terms, all documents incorporated by reference and your relationship with us shall be governed by, construed, and enforced in accordance with the laws of the Province of Ontario, Canada, (and any Canadian federal laws applicable therein) as it is applied to agreements entered and to be performed entirely within such province.&nbsp;</p>
                                            <p>You hereby agree to irrevocably and unconditionally submit to the exclusive jurisdiction of the courts and tribunals of Ontario, Canada (including the Federal courts and tribunals as applicable therein) to settle any disputes arising out of or in any way related to these Terms, all documents incorporated by reference and your relationship with us. </p>
                                            <p>Notwithstanding the foregoing, you agree that we may apply to a court in any jurisdiction in order to obtain injunctive relief and/or any other available equitable or legal remedy regarding any matter relating to intellectual property rights or proprietary rights.</p>
                                            <p>You agree that the UN Convention on Contracts for the International Sale of Goods shall not apply or govern these Terms.&nbsp;</p>
                                            <p><strong>Set-Off</strong></p>
                                            <p>We may set-off any amounts owing to us against any amounts we may owe you.&nbsp;</p>
                                            <p><strong>Severability&nbsp;</strong></p>
                                            <p>If any provision of these Terms (or any part thereof) is found to be unlawful, void, or for any reason unenforceable, then that provision, or the relevant part thereof, shall be deemed severable from this agreement and shall not affect the validity and enforceability of any remaining provisions.</p>
                                            <p><strong>No Interpretation Against Drafter</strong></p>
                                            <p>If an ambiguity or question of intent arises with respect to any provision of these Terms, the Terms shall be construed as if drafted jointly by the parties and no presumption or burden of proof will arise favouring or disfavouring either party by virtue of authorship of any of the provisions of these Terms.</p>
                                            <p><strong>Other Interpretation Matters</strong></p>
                                            <p>You agree that any provision of these Terms in which you agree or which obligates you to limit the liability of, hold harmless or indemnify any person or entity who is not a party to these Terms (such as our directors, officers, shareholders and employees) that such covenants and obligations are accepted by us as agent and trustee for each such third-party. We declare ourselves trustee of such covenants and obligations for each such third party; such covenants and obligations may be enforced by us on behalf of any such third party.&nbsp;</p>
                                            <p><strong>Waiver of Class Proceedings and Trial By Jury</strong></p>
                                            <p>To the extent permitted by law, you hereby waive your right to participate in any class action lawsuits against us, our contractors, employees, shareholders, successors, assigns and directors.&nbsp;</p>
                                            <p>To the extent permitted by law, you further waive any right to a trial by jury, should such a right exist, in relation to any legal dispute connected to or in any way arising out of these Terms.</p>
                                            <p><strong>Incorporation by Reference</strong></p>
                                            <p>All policies referred to in these Terms or anywhere on the U-Greet Platform are hereby incorporated by reference, including but not limited to our Privacy Policy.</p>
                                            <p><strong>Termination</strong></p>
                                            <p>You can stop using the U-Greet Platform at any time. Please contact us at <a href="mailto:info@u-greet.com">info@u-greet.com</a> to terminate your account. Notwithstanding your decision to delete your account or no longer use the U-Greet Platform, you agree to pay all fees and taxes as set out in these Terms in connection with your account on the U-Greet Platform.</p>
                                            <p>We also reserve the right to suspend your account or access to the U-Greet Platform at any time, with or without reason or cause, and with or without notice. We make no guarantees as to the ongoing availability of the platform, and may decide, without advanced notice, to cease offering the platform.&nbsp;</p>
                                            <p>The cancellation, suspension or termination of access to the U-Greet Platform shall not terminate this agreement.  In particular, and without limiting the generality of the foregoing, any provision concerning the limitation of our liability, your indemnification obligations, settling disputes (including the jurisdiction and choice of law) shall remain binding.</p>
                                            <p><strong>Assignment of this Agreement</strong></p>
                                            <p>These Terms shall enure to the benefit of and are binding upon the parties and their respective successors and permitted assigns.&nbsp;</p>
                                            <p>You agree that we may assign this agreement to any successor or assignee of our choosing, whether pursuant to the purchase of the U-Greet Platform by a third party, the transfer of control of U-Greet Inc. or otherwise.&nbsp;</p>
                                            <p>You are not authorized to assign this agreement, or control of your account on the platform.&nbsp;</p>
                                            <p><strong>Right to Seek Injunction</strong></p>
                                            <p>Violation of these Terms may cause us irreparable harm and, therefore, you agree that we will be entitled to seek extraordinary relief including, but not limited to, temporary restraining orders, preliminary injunctions and permanent injunctions without the necessity of posting a bond or other security, in addition to and without prejudice to any other rights or remedies that we may have for a breach of these Terms.</p>
                                            <p><strong>Waiver</strong></p>
                                            <p>Our failure to enforce any right or provision of these Terms will not be deemed a waiver of such right or provision.</p>
                                            <p><strong>New Features</strong></p>
                                            <p>Any new features, or new functionality, that augment or enhance the current U-Greet Platform, including the release of new versions, new products or services, tools and resources, shall be subject to these Terms.&nbsp;</p>
                                            <p><strong>Entire Agreement</strong></p>
                                            <p>This is the entire agreement between the parties relating to the matters contained herein and shall not be modified except (i) by publication of a subsequent version of these Terms as contemplated herein; or (ii) in writing, in an addendum or other agreement, signed by both you and us.</p>
                                        </div>

                                   



                                    </article>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <FooterWebsite />
            </div>
        </div>
    );
};

export default TermsConditions;
